spring:
  datasource:
    url: jdbc:mysql://localhost:3306/team_project2?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 8112


  jpa:
    show-sql: true
    properties:
      hibernate:
        use_sql_comments: true
        format_sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQLDialect  # 추가한 부분 유지

  redis:
    host: localhost
    port: 6379
    password: 8112

logging:
  level:
    ROOT: INFO
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG

jwt:
  secret: secretsecretsecretkeykeykeykeykeykey
  expiration_time: 3600 # 1시간