spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MYSQL;NON_KEYWORDS=USER

  redis:
    host: localhost
    port: 6379
    password:

jwt:
  secret: secretsecretsecretkeykeykeykeykeykey
  login_expiration_time: 7200 #2시간
  queue_expiration_time: 3600 # 1시간