spring:
  datasource:
    url: jdbc:mysql://localhost:3306/{??? ?? ?? ?? ?? ??? ???.}/
    username: root
    password:

  jpa:
    show-sql: true
    properties:
      hibernate:
        use_sql_comments: true
        format_sql: true
    hibernate:
      ddl-auto: create

logging:
  level:
    ROOT: INFO
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG

jwt:
  secret: secretsecretsecretkeykeykeykeykeykey
  expiration_time: 3600 # 1시간