spring:
  datasource:
    url: jdbc:mysql://localhost:3306/{??? ?? ?? ?? ?? ??? ???.}/
    username: root
    password:

  jpa:
    show-sql: true
    properties:
      hibernate:
        use_sql_comments: true
        format_sql: true
    hibernate:
      ddl-auto: create
  redis:
    host: localhost
    port: 6379
    password:

server:
  tomcat:
    threads:
      min-spare: 50

logging:
  level:
    ROOT: INFO
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG

jwt:
  secretKey: concert_jwt_secretconcert_jwt_secretconcert_jwt_secretconcert_jwt_secretconcert_jwt_secret
  expiration: 1800000